<?php

return [
    'version' => 1,

    'export_formats' => [
        ['id' => 'png', 'label' => 'PNG (transparência)', 'ext' => 'png', 'mime' => 'image/png', 'hint' => 'Photoshop, Affinity, web'],
        ['id' => 'jpg', 'label' => 'JPG (foto)', 'ext' => 'jpg', 'mime' => 'image/jpeg', 'hint' => 'Redes sociais, sites'],
        ['id' => 'svg', 'label' => 'SVG (vetor)', 'ext' => 'svg', 'mime' => 'image/svg+xml', 'hint' => 'CorelDRAW, Affinity, Illustrator'],
        ['id' => 'psd', 'label' => 'PSD (camadas)', 'ext' => 'psd', 'mime' => 'application/vnd.adobe.photoshop', 'hint' => 'Photoshop, Affinity Photo'],
        ['id' => 'pdf', 'label' => 'PDF (impressão)', 'ext' => 'pdf', 'mime' => 'application/pdf', 'hint' => 'CorelDRAW, Affinity, impressão'],
        ['id' => 'json', 'label' => 'Projeto CriaSys (.json)', 'ext' => 'json', 'mime' => 'application/json', 'hint' => 'Reabrir e editar depois'],
    ],

    'groups' => [
        'custom' => 'Personalizado',
        'instagram' => 'Instagram',
        'facebook' => 'Facebook',
        'linkedin' => 'LinkedIn',
        'twitter' => 'X / Twitter',
        'youtube' => 'YouTube',
        'tiktok' => 'TikTok',
        'pinterest' => 'Pinterest',
        'whatsapp' => 'WhatsApp',
        'shorts' => 'Shorts / Reels / vertical',
        'avatars' => 'Avatares & perfis (circular)',
        'web' => 'Sites & banners',
        'stories' => 'Stories / vertical',
        'ratios' => 'Proporções genéricas',
        'marketing' => 'Panfletos, folders & cartões',
        'print' => 'Impressão',
    ],

    'presets' => [
        'custom' => ['name' => 'Personalizado', 'group' => 'custom', 'width' => 1920, 'height' => 1080, 'icon' => '▭', 'aspect' => '16:9'],
        // ── Instagram ──
        'ig_feed_square' => ['name' => 'Feed quadrado 1:1', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '◎', 'aspect' => '1:1'],
        'ig_feed_portrait' => ['name' => 'Feed retrato 4:5', 'group' => 'instagram', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'ig_feed_portrait_34' => ['name' => 'Feed retrato 3:4', 'group' => 'instagram', 'width' => 1080, 'height' => 1440, 'icon' => '▯', 'aspect' => '3:4'],
        'ig_feed_landscape' => ['name' => 'Feed paisagem 1.91:1', 'group' => 'instagram', 'width' => 1080, 'height' => 566, 'icon' => '▭', 'aspect' => '1.91:1'],
        'ig_carousel_square' => ['name' => 'Carrossel slide quadrado', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '▢', 'aspect' => '1:1'],
        'ig_carousel_portrait' => ['name' => 'Carrossel slide 4:5', 'group' => 'instagram', 'width' => 1080, 'height' => 1350, 'icon' => '▢', 'aspect' => '4:5'],
        'ig_reels' => ['name' => 'Reels capa 9:16', 'group' => 'instagram', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'ig_reels_cover_sq' => ['name' => 'Reels capa quadrada (grid)', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '◎', 'aspect' => '1:1'],
        'ig_story' => ['name' => 'Story 9:16', 'group' => 'instagram', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'ig_highlight' => ['name' => 'Destaque (capa circular)', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '◉', 'aspect' => '1:1', 'hint' => 'Desenhe no centro — recorte circular no app'],
        'ig_profile' => ['name' => 'Foto de perfil 320', 'group' => 'instagram', 'width' => 320, 'height' => 320, 'icon' => '◉', 'aspect' => '1:1'],
        'ig_profile_hd' => ['name' => 'Foto de perfil 800', 'group' => 'instagram', 'width' => 800, 'height' => 800, 'icon' => '◉', 'aspect' => '1:1'],
        'ig_ad_square' => ['name' => 'Anúncio quadrado', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '◎', 'aspect' => '1:1'],
        'ig_ad_portrait' => ['name' => 'Anúncio retrato 4:5', 'group' => 'instagram', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'ig_ad_story' => ['name' => 'Anúncio story 9:16', 'group' => 'instagram', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'ig_shopping' => ['name' => 'Shopping / produto', 'group' => 'instagram', 'width' => 1080, 'height' => 1080, 'icon' => '🛒', 'aspect' => '1:1'],

        // ── Facebook ──
        'fb_feed' => ['name' => 'Post feed 1.91:1', 'group' => 'facebook', 'width' => 1200, 'height' => 630, 'icon' => 'f', 'aspect' => '1.91:1'],
        'fb_feed_square' => ['name' => 'Post feed quadrado', 'group' => 'facebook', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'fb_feed_portrait' => ['name' => 'Post feed retrato 4:5', 'group' => 'facebook', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'fb_cover' => ['name' => 'Capa página', 'group' => 'facebook', 'width' => 820, 'height' => 312, 'icon' => '▬', 'aspect' => '2.63:1'],
        'fb_cover_hd' => ['name' => 'Capa página HD', 'group' => 'facebook', 'width' => 1640, 'height' => 624, 'icon' => '▬', 'aspect' => '2.63:1'],
        'fb_group_cover' => ['name' => 'Capa grupo', 'group' => 'facebook', 'width' => 1640, 'height' => 856, 'icon' => '▬', 'aspect' => '1.92:1'],
        'fb_story' => ['name' => 'Story 9:16', 'group' => 'facebook', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'fb_reels' => ['name' => 'Reels 9:16', 'group' => 'facebook', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'fb_event' => ['name' => 'Evento 16:9', 'group' => 'facebook', 'width' => 1920, 'height' => 1080, 'icon' => '📅', 'aspect' => '16:9'],
        'fb_ad_square' => ['name' => 'Anúncio quadrado', 'group' => 'facebook', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'fb_ad_portrait' => ['name' => 'Anúncio retrato 4:5', 'group' => 'facebook', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'fb_ad_landscape' => ['name' => 'Anúncio paisagem', 'group' => 'facebook', 'width' => 1200, 'height' => 628, 'icon' => '▭', 'aspect' => '1.91:1'],
        'fb_marketplace' => ['name' => 'Marketplace produto', 'group' => 'facebook', 'width' => 1200, 'height' => 1200, 'icon' => '🛒', 'aspect' => '1:1'],
        'fb_profile' => ['name' => 'Foto de perfil', 'group' => 'facebook', 'width' => 360, 'height' => 360, 'icon' => '◉', 'aspect' => '1:1'],

        // ── LinkedIn ──
        'li_feed' => ['name' => 'Post feed', 'group' => 'linkedin', 'width' => 1200, 'height' => 627, 'icon' => 'in', 'aspect' => '1.91:1'],
        'li_feed_square' => ['name' => 'Post quadrado', 'group' => 'linkedin', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'li_feed_portrait' => ['name' => 'Post retrato 4:5', 'group' => 'linkedin', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'li_cover' => ['name' => 'Capa perfil', 'group' => 'linkedin', 'width' => 1584, 'height' => 396, 'icon' => '▬', 'aspect' => '4:1'],
        'li_article' => ['name' => 'Artigo / blog 16:9', 'group' => 'linkedin', 'width' => 1280, 'height' => 720, 'icon' => '📄', 'aspect' => '16:9'],
        'li_ad' => ['name' => 'Anúncio feed', 'group' => 'linkedin', 'width' => 1200, 'height' => 628, 'icon' => '◎', 'aspect' => '1.91:1'],
        'li_ad_square' => ['name' => 'Anúncio quadrado', 'group' => 'linkedin', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'li_carousel' => ['name' => 'Carrossel documento', 'group' => 'linkedin', 'width' => 1080, 'height' => 1080, 'icon' => '▢', 'aspect' => '1:1'],
        'li_profile' => ['name' => 'Foto de perfil', 'group' => 'linkedin', 'width' => 400, 'height' => 400, 'icon' => '◉', 'aspect' => '1:1'],
        'li_company_logo' => ['name' => 'Logo empresa', 'group' => 'linkedin', 'width' => 300, 'height' => 300, 'icon' => '◉', 'aspect' => '1:1'],

        // ── X / Twitter ──
        'x_post' => ['name' => 'Post 16:9', 'group' => 'twitter', 'width' => 1600, 'height' => 900, 'icon' => '𝕏', 'aspect' => '16:9'],
        'x_post_square' => ['name' => 'Post quadrado', 'group' => 'twitter', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'x_post_portrait' => ['name' => 'Post retrato 4:5', 'group' => 'twitter', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'x_header' => ['name' => 'Capa perfil', 'group' => 'twitter', 'width' => 1500, 'height' => 500, 'icon' => '▬', 'aspect' => '3:1'],
        'x_card' => ['name' => 'Card link', 'group' => 'twitter', 'width' => 800, 'height' => 418, 'icon' => '🔗', 'aspect' => '1.91:1'],
        'x_profile' => ['name' => 'Foto de perfil', 'group' => 'twitter', 'width' => 400, 'height' => 400, 'icon' => '◉', 'aspect' => '1:1'],
        'x_fleet' => ['name' => 'Story / Fleet 9:16', 'group' => 'twitter', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],

        // ── YouTube ──
        'yt_thumb' => ['name' => 'Thumbnail 16:9', 'group' => 'youtube', 'width' => 1280, 'height' => 720, 'icon' => '▶', 'aspect' => '16:9'],
        'yt_thumb_hd' => ['name' => 'Thumbnail Full HD', 'group' => 'youtube', 'width' => 1920, 'height' => 1080, 'icon' => '▶', 'aspect' => '16:9'],
        'yt_thumb_4k' => ['name' => 'Thumbnail 4K 16:9', 'group' => 'youtube', 'width' => 3840, 'height' => 2160, 'icon' => '▶', 'aspect' => '16:9'],
        'yt_banner' => ['name' => 'Banner canal (TV)', 'group' => 'youtube', 'width' => 2560, 'height' => 1440, 'icon' => '▬', 'aspect' => '16:9'],
        'yt_banner_safe' => ['name' => 'Banner canal (área segura)', 'group' => 'youtube', 'width' => 1546, 'height' => 423, 'icon' => '▬', 'aspect' => '3.65:1'],
        'yt_shorts' => ['name' => 'Shorts capa 9:16', 'group' => 'youtube', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'yt_shorts_thumb' => ['name' => 'Shorts thumb 9:16 HD', 'group' => 'youtube', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'yt_community_sq' => ['name' => 'Community post quadrado', 'group' => 'youtube', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],
        'yt_community_wide' => ['name' => 'Community post 16:9', 'group' => 'youtube', 'width' => 1280, 'height' => 720, 'icon' => '▭', 'aspect' => '16:9'],
        'yt_profile' => ['name' => 'Foto de perfil canal', 'group' => 'youtube', 'width' => 800, 'height' => 800, 'icon' => '◉', 'aspect' => '1:1'],
        'yt_end_screen' => ['name' => 'End screen elemento', 'group' => 'youtube', 'width' => 300, 'height' => 300, 'icon' => '◉', 'aspect' => '1:1'],

        // ── TikTok ──
        'tt_video' => ['name' => 'Vídeo / capa 9:16', 'group' => 'tiktok', 'width' => 1080, 'height' => 1920, 'icon' => '♪', 'aspect' => '9:16'],
        'tt_profile' => ['name' => 'Foto perfil 200', 'group' => 'tiktok', 'width' => 200, 'height' => 200, 'icon' => '◉', 'aspect' => '1:1'],
        'tt_profile_hd' => ['name' => 'Foto perfil 400', 'group' => 'tiktok', 'width' => 400, 'height' => 400, 'icon' => '◉', 'aspect' => '1:1'],
        'tt_ad_portrait' => ['name' => 'Anúncio 9:16', 'group' => 'tiktok', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'tt_ad_square' => ['name' => 'Anúncio quadrado', 'group' => 'tiktok', 'width' => 1080, 'height' => 1080, 'icon' => '□', 'aspect' => '1:1'],

        // ── Pinterest ──
        'pin_standard' => ['name' => 'Pin padrão 2:3', 'group' => 'pinterest', 'width' => 1000, 'height' => 1500, 'icon' => '📌', 'aspect' => '2:3'],
        'pin_square' => ['name' => 'Pin quadrado', 'group' => 'pinterest', 'width' => 1000, 'height' => 1000, 'icon' => '□', 'aspect' => '1:1'],
        'pin_long' => ['name' => 'Pin longo 1:2.1', 'group' => 'pinterest', 'width' => 1000, 'height' => 2100, 'icon' => '📌', 'aspect' => '1:2.1'],
        'pin_story' => ['name' => 'Pin story 9:16', 'group' => 'pinterest', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'pin_profile' => ['name' => 'Foto de perfil', 'group' => 'pinterest', 'width' => 165, 'height' => 165, 'icon' => '◉', 'aspect' => '1:1'],

        // ── WhatsApp ──
        'wa_status' => ['name' => 'Status 9:16', 'group' => 'whatsapp', 'width' => 1080, 'height' => 1920, 'icon' => '💬', 'aspect' => '9:16'],
        'wa_profile' => ['name' => 'Foto de perfil', 'group' => 'whatsapp', 'width' => 500, 'height' => 500, 'icon' => '◉', 'aspect' => '1:1'],
        'wa_sticker' => ['name' => 'Sticker 512', 'group' => 'whatsapp', 'width' => 512, 'height' => 512, 'icon' => '◉', 'aspect' => '1:1'],

        // ── Shorts / Reels / vertical (genérico) ──
        'short_9_16' => ['name' => 'Vertical 9:16 padrão', 'group' => 'shorts', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'short_9_16_hd' => ['name' => 'Vertical 9:16 Full HD', 'group' => 'shorts', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'short_9_16_720' => ['name' => 'Vertical 9:16 720p', 'group' => 'shorts', 'width' => 720, 'height' => 1280, 'icon' => '▲', 'aspect' => '9:16'],
        'short_4_5' => ['name' => 'Vertical 4:5 (feed)', 'group' => 'shorts', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'short_snap' => ['name' => 'Snapchat story', 'group' => 'shorts', 'width' => 1080, 'height' => 1920, 'icon' => '👻', 'aspect' => '9:16'],
        'short_kwai' => ['name' => 'Kwai vertical', 'group' => 'shorts', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'short_threads' => ['name' => 'Threads post quadrado', 'group' => 'shorts', 'width' => 1080, 'height' => 1080, 'icon' => '◎', 'aspect' => '1:1'],
        'short_spotify_canvas' => ['name' => 'Spotify Canvas 9:16', 'group' => 'shorts', 'width' => 720, 'height' => 1280, 'icon' => '♫', 'aspect' => '9:16'],

        // ── Avatares & perfis (canvas quadrado → recorte circular) ──
        'avatar_xs' => ['name' => 'Avatar 128 (Discord pequeno)', 'group' => 'avatars', 'width' => 128, 'height' => 128, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_sm' => ['name' => 'Avatar 200', 'group' => 'avatars', 'width' => 200, 'height' => 200, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_md' => ['name' => 'Avatar 400', 'group' => 'avatars', 'width' => 400, 'height' => 400, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_lg' => ['name' => 'Avatar 512 (Discord/Telegram)', 'group' => 'avatars', 'width' => 512, 'height' => 512, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_xl' => ['name' => 'Avatar 800 (YouTube/Twitch)', 'group' => 'avatars', 'width' => 800, 'height' => 800, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_2k' => ['name' => 'Avatar 1024 (alta res.)', 'group' => 'avatars', 'width' => 1024, 'height' => 1024, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_ig' => ['name' => 'Instagram perfil 320', 'group' => 'avatars', 'width' => 320, 'height' => 320, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_fb' => ['name' => 'Facebook perfil 360', 'group' => 'avatars', 'width' => 360, 'height' => 360, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_google' => ['name' => 'Google Business 720', 'group' => 'avatars', 'width' => 720, 'height' => 720, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_spotify' => ['name' => 'Spotify artista 750', 'group' => 'avatars', 'width' => 750, 'height' => 750, 'icon' => '◉', 'aspect' => '1:1'],
        'avatar_steam' => ['name' => 'Steam avatar 184', 'group' => 'avatars', 'width' => 184, 'height' => 184, 'icon' => '◉', 'aspect' => '1:1'],

        // ── Web & banners ──
        'web_hero' => ['name' => 'Hero site 1920', 'group' => 'web', 'width' => 1920, 'height' => 800, 'icon' => '🌐', 'aspect' => '2.4:1'],
        'web_hero_full' => ['name' => 'Hero full screen 16:9', 'group' => 'web', 'width' => 1920, 'height' => 1080, 'icon' => '🌐', 'aspect' => '16:9'],
        'web_banner_leader' => ['name' => 'Leaderboard 728×90', 'group' => 'web', 'width' => 728, 'height' => 90, 'icon' => '▭', 'aspect' => '8.09:1'],
        'web_banner_medium' => ['name' => 'Medium rectangle 300×250', 'group' => 'web', 'width' => 300, 'height' => 250, 'icon' => '▢', 'aspect' => '1.2:1'],
        'web_banner_large' => ['name' => 'Large rectangle 336×280', 'group' => 'web', 'width' => 336, 'height' => 280, 'icon' => '▢', 'aspect' => '1.2:1'],
        'web_banner_sky' => ['name' => 'Skyscraper 160×600', 'group' => 'web', 'width' => 160, 'height' => 600, 'icon' => '▯', 'aspect' => '1:3.75'],
        'web_banner_wide' => ['name' => 'Wide banner 970×250', 'group' => 'web', 'width' => 970, 'height' => 250, 'icon' => '▬', 'aspect' => '3.88:1'],
        'web_banner_half' => ['name' => 'Half page 300×600', 'group' => 'web', 'width' => 300, 'height' => 600, 'icon' => '▯', 'aspect' => '1:2'],
        'web_banner_mobile' => ['name' => 'Mobile banner 320×50', 'group' => 'web', 'width' => 320, 'height' => 50, 'icon' => '▭', 'aspect' => '6.4:1'],
        'web_banner_billboard' => ['name' => 'Billboard 970×250', 'group' => 'web', 'width' => 970, 'height' => 250, 'icon' => '▬', 'aspect' => '3.88:1'],
        'web_og' => ['name' => 'Open Graph / SEO', 'group' => 'web', 'width' => 1200, 'height' => 630, 'icon' => '🔗', 'aspect' => '1.91:1'],
        'web_twitter_card' => ['name' => 'Twitter/X card', 'group' => 'web', 'width' => 800, 'height' => 418, 'icon' => '🔗', 'aspect' => '1.91:1'],
        'web_email_header' => ['name' => 'E-mail header 600', 'group' => 'web', 'width' => 600, 'height' => 200, 'icon' => '✉', 'aspect' => '3:1'],
        'web_email_banner' => ['name' => 'E-mail banner 600×300', 'group' => 'web', 'width' => 600, 'height' => 300, 'icon' => '✉', 'aspect' => '2:1'],
        'web_favicon' => ['name' => 'Favicon pack 512', 'group' => 'web', 'width' => 512, 'height' => 512, 'icon' => '◉', 'aspect' => '1:1'],

        // ── Stories genérico ──
        'story_vertical' => ['name' => 'Story 9:16', 'group' => 'stories', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'story_vertical_hd' => ['name' => 'Story Full HD 9:16', 'group' => 'stories', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'story_safe_title' => ['name' => 'Story com faixa título', 'group' => 'stories', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16', 'hint' => 'Área segura topo/base 250px'],

        // ── Proporções genéricas ──
        'ratio_1_1' => ['name' => 'Quadrado 1:1 — 1080', 'group' => 'ratios', 'width' => 1080, 'height' => 1080, 'icon' => '◎', 'aspect' => '1:1'],
        'ratio_1_1_2k' => ['name' => 'Quadrado 1:1 — 2000', 'group' => 'ratios', 'width' => 2000, 'height' => 2000, 'icon' => '◎', 'aspect' => '1:1'],
        'ratio_4_5' => ['name' => 'Retrato 4:5', 'group' => 'ratios', 'width' => 1080, 'height' => 1350, 'icon' => '▯', 'aspect' => '4:5'],
        'ratio_3_4' => ['name' => 'Retrato 3:4', 'group' => 'ratios', 'width' => 1080, 'height' => 1440, 'icon' => '▯', 'aspect' => '3:4'],
        'ratio_2_3' => ['name' => 'Retrato 2:3', 'group' => 'ratios', 'width' => 1000, 'height' => 1500, 'icon' => '▯', 'aspect' => '2:3'],
        'ratio_9_16' => ['name' => 'Retrato 9:16', 'group' => 'ratios', 'width' => 1080, 'height' => 1920, 'icon' => '▲', 'aspect' => '9:16'],
        'ratio_16_9' => ['name' => 'Paisagem 16:9 — 1920', 'group' => 'ratios', 'width' => 1920, 'height' => 1080, 'icon' => '▭', 'aspect' => '16:9'],
        'ratio_16_9_hd' => ['name' => 'Paisagem 16:9 — 1280', 'group' => 'ratios', 'width' => 1280, 'height' => 720, 'icon' => '▭', 'aspect' => '16:9'],
        'ratio_16_9_4k' => ['name' => 'Paisagem 16:9 — 4K', 'group' => 'ratios', 'width' => 3840, 'height' => 2160, 'icon' => '▭', 'aspect' => '16:9'],
        'ratio_4_3' => ['name' => 'Paisagem 4:3', 'group' => 'ratios', 'width' => 1600, 'height' => 1200, 'icon' => '▭', 'aspect' => '4:3'],
        'ratio_3_2' => ['name' => 'Paisagem 3:2', 'group' => 'ratios', 'width' => 1500, 'height' => 1000, 'icon' => '▭', 'aspect' => '3:2'],
        'ratio_21_9' => ['name' => 'Ultrawide 21:9', 'group' => 'ratios', 'width' => 2560, 'height' => 1080, 'icon' => '▬', 'aspect' => '21:9'],
        'ratio_1_91_1' => ['name' => 'Paisagem 1.91:1 (OG)', 'group' => 'ratios', 'width' => 1200, 'height' => 628, 'icon' => '▭', 'aspect' => '1.91:1'],
        'ratio_a4_portrait' => ['name' => 'A4 retrato (tela)', 'group' => 'ratios', 'width' => 1240, 'height' => 1754, 'icon' => '📄', 'aspect' => 'A4'],
        'ratio_a4_landscape' => ['name' => 'A4 paisagem (tela)', 'group' => 'ratios', 'width' => 1754, 'height' => 1240, 'icon' => '📄', 'aspect' => 'A4'],

        // ── Panfletos, folders & cartões (300 dpi) ──
        'mkt_flyer_a4' => ['name' => 'Panfleto A4 retrato', 'group' => 'marketing', 'width' => 2480, 'height' => 3508, 'icon' => '📄', 'aspect' => 'A4'],
        'mkt_flyer_a4_land' => ['name' => 'Panfleto A4 paisagem', 'group' => 'marketing', 'width' => 3508, 'height' => 2480, 'icon' => '📄', 'aspect' => 'A4'],
        'mkt_flyer_a5' => ['name' => 'Panfleto A5 retrato', 'group' => 'marketing', 'width' => 1748, 'height' => 2480, 'icon' => '📄', 'aspect' => 'A5'],
        'mkt_flyer_a5_land' => ['name' => 'Panfleto A5 paisagem', 'group' => 'marketing', 'width' => 2480, 'height' => 1748, 'icon' => '📄', 'aspect' => 'A5'],
        'mkt_flyer_a6' => ['name' => 'Panfleto A6 (metade A5)', 'group' => 'marketing', 'width' => 1240, 'height' => 1748, 'icon' => '📄', 'aspect' => 'A6'],
        'mkt_flyer_dl' => ['name' => 'Panfleto DL (1/3 A4)', 'group' => 'marketing', 'width' => 1169, 'height' => 2480, 'icon' => '📄', 'aspect' => 'DL'],
        'mkt_flyer_half_a4' => ['name' => 'Panfleto meia página A4', 'group' => 'marketing', 'width' => 2480, 'height' => 1754, 'icon' => '📄', 'aspect' => 'A4½'],
        'mkt_folder_a4_closed' => ['name' => 'Folder A4 fechado (frente)', 'group' => 'marketing', 'width' => 2480, 'height' => 3508, 'icon' => '📁', 'aspect' => 'A4'],
        'mkt_folder_a4_open' => ['name' => 'Folder A4 aberto (interno)', 'group' => 'marketing', 'width' => 7016, 'height' => 2480, 'icon' => '📁', 'aspect' => '3×A4'],
        'mkt_folder_a4_trifold' => ['name' => 'Folder tri-fold A4', 'group' => 'marketing', 'width' => 3508, 'height' => 2480, 'icon' => '📁', 'aspect' => 'A4'],
        'mkt_card_visit_br' => ['name' => 'Cartão visita 85×55 mm', 'group' => 'marketing', 'width' => 1004, 'height' => 650, 'icon' => '💳', 'aspect' => '85×55'],
        'mkt_card_visit_us' => ['name' => 'Cartão visita 3.5×2 pol.', 'group' => 'marketing', 'width' => 1050, 'height' => 600, 'icon' => '💳', 'aspect' => '3.5×2"'],
        'mkt_card_postcard' => ['name' => 'Postal A6', 'group' => 'marketing', 'width' => 1748, 'height' => 1240, 'icon' => '✉', 'aspect' => 'A6'],
        'mkt_invite_10x15' => ['name' => 'Convite 10×15 cm', 'group' => 'marketing', 'width' => 1181, 'height' => 1772, 'icon' => '💌', 'aspect' => '10×15'],
        'mkt_invite_15x21' => ['name' => 'Convite A5 15×21 cm', 'group' => 'marketing', 'width' => 1772, 'height' => 2480, 'icon' => '💌', 'aspect' => 'A5'],
        'mkt_badge' => ['name' => 'Crachá 54×86 mm', 'group' => 'marketing', 'width' => 638, 'height' => 1016, 'icon' => '🪪', 'aspect' => 'crachá'],
        'mkt_menu_a4' => ['name' => 'Cardápio A4', 'group' => 'marketing', 'width' => 2480, 'height' => 3508, 'icon' => '📋', 'aspect' => 'A4'],
        'mkt_coupon' => ['name' => 'Cupom / voucher 800×400', 'group' => 'marketing', 'width' => 800, 'height' => 400, 'icon' => '🎟', 'aspect' => '2:1'],
        'mkt_rollup' => ['name' => 'Banner roll-up 80×200 cm', 'group' => 'marketing', 'width' => 9449, 'height' => 23622, 'icon' => '🎪', 'aspect' => '80×200', 'hint' => 'Alta resolução — pode demorar ao exportar'],
        'mkt_rollup_preview' => ['name' => 'Roll-up preview (1200×3000)', 'group' => 'marketing', 'width' => 1200, 'height' => 3000, 'icon' => '🎪', 'aspect' => '2:5'],

        // ── Impressão ──
        'print_a4' => ['name' => 'A4 retrato 300dpi', 'group' => 'print', 'width' => 2480, 'height' => 3508, 'icon' => '🖨', 'aspect' => 'A4'],
        'print_a4_land' => ['name' => 'A4 paisagem 300dpi', 'group' => 'print', 'width' => 3508, 'height' => 2480, 'icon' => '🖨', 'aspect' => 'A4'],
        'print_a5' => ['name' => 'A5 retrato 300dpi', 'group' => 'print', 'width' => 1748, 'height' => 2480, 'icon' => '🖨', 'aspect' => 'A5'],
        'print_a5_land' => ['name' => 'A5 paisagem 300dpi', 'group' => 'print', 'width' => 2480, 'height' => 1748, 'icon' => '🖨', 'aspect' => 'A5'],
        'print_a3' => ['name' => 'A3 retrato 300dpi', 'group' => 'print', 'width' => 3508, 'height' => 4961, 'icon' => '🖨', 'aspect' => 'A3'],
        'print_a3_land' => ['name' => 'A3 paisagem 300dpi', 'group' => 'print', 'width' => 4961, 'height' => 3508, 'icon' => '🖨', 'aspect' => 'A3'],
        'print_a6' => ['name' => 'A6 retrato 300dpi', 'group' => 'print', 'width' => 1240, 'height' => 1748, 'icon' => '🖨', 'aspect' => 'A6'],
        'print_letter' => ['name' => 'Carta US Letter 300dpi', 'group' => 'print', 'width' => 2550, 'height' => 3300, 'icon' => '🖨', 'aspect' => 'Letter'],
        'print_letter_land' => ['name' => 'Carta US paisagem 300dpi', 'group' => 'print', 'width' => 3300, 'height' => 2550, 'icon' => '🖨', 'aspect' => 'Letter'],
        'print_poster_a2' => ['name' => 'Poster A2 300dpi', 'group' => 'print', 'width' => 4961, 'height' => 7016, 'icon' => '🖼', 'aspect' => 'A2'],
        'print_poster' => ['name' => 'Poster 50×70 cm 300dpi', 'group' => 'print', 'width' => 5906, 'height' => 8268, 'icon' => '🖼', 'aspect' => '50×70'],
        'print_poster_60x90' => ['name' => 'Poster 60×90 cm 300dpi', 'group' => 'print', 'width' => 7087, 'height' => 10630, 'icon' => '🖼', 'aspect' => '60×90'],
        'print_photo_10x15' => ['name' => 'Foto 10×15 cm 300dpi', 'group' => 'print', 'width' => 1181, 'height' => 1772, 'icon' => '📷', 'aspect' => '10×15'],
        'print_photo_13x18' => ['name' => 'Foto 13×18 cm 300dpi', 'group' => 'print', 'width' => 1535, 'height' => 2126, 'icon' => '📷', 'aspect' => '13×18'],
        'print_photo_20x30' => ['name' => 'Foto 20×30 cm 300dpi', 'group' => 'print', 'width' => 2362, 'height' => 3543, 'icon' => '📷', 'aspect' => '20×30'],
    ],

    'templates' => [
        'story_quote' => [
            'name' => 'Story citação',
            'description' => 'Caixa preta + Bebas — frase de impacto',
            'preset' => 'ig_story',
            'group' => 'stories',
            'viral' => true,
            'background' => ['color' => '#09090b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Caixa citação', 'x' => 0.05, 'y' => 0.4, 'w' => 0.9, 'h' => 0.2, 'fill' => '#000000', 'opacity' => 88, 'rx' => 8, 'ry' => 8],
                ['kind' => 'text', 'name' => 'Citação', 'x' => 0.5, 'y' => 0.5, 'text' => 'SUA FRASE AQUI', 'fontSize' => 64, 'fill' => '#ffffff', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 40],
            ],
        ],
        'ig_promo_sale' => [
            'name' => 'Post promoção',
            'description' => 'Destaque vermelho + headline',
            'preset' => 'ig_feed_square',
            'group' => 'instagram',
            'background' => ['color' => '#fafafa', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Faixa promo', 'x' => 0, 'y' => 0.72, 'w' => 1, 'h' => 0.28, 'fill' => '#dc2626', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Headline', 'x' => 0.5, 'y' => 0.82, 'text' => 'PROMOÇÃO', 'fontSize' => 72, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Subtítulo', 'x' => 0.5, 'y' => 0.92, 'text' => 'Até 50% OFF', 'fontSize' => 36, 'fill' => '#fef2f2', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'yt_thumb_bold' => [
            'name' => 'Thumbnail YouTube',
            'description' => 'Barra inferior + título impacto',
            'preset' => 'yt_thumb',
            'group' => 'youtube',
            'background' => ['color' => '#27272a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Barra inferior', 'x' => 0, 'y' => 0.78, 'w' => 1, 'h' => 0.22, 'fill' => '#7c3aed', 'opacity' => 95],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.04, 'y' => 0.86, 'text' => 'TÍTULO DO VÍDEO', 'fontSize' => 56, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'left', 'originY' => 'center'],
            ],
        ],
        'fb_event_card' => [
            'name' => 'Card evento Facebook',
            'description' => 'Data + título evento',
            'preset' => 'fb_feed',
            'group' => 'facebook',
            'background' => ['color' => '#1e3a5f', 'opacity' => 100],
            'objects' => [
                ['kind' => 'circle', 'name' => 'Destaque', 'x' => 0.08, 'y' => 0.5, 'r' => 0.12, 'fill' => '#2563eb', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Data', 'x' => 0.08, 'y' => 0.5, 'text' => '15\nJUL', 'fontSize' => 28, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Evento', 'x' => 0.28, 'y' => 0.42, 'text' => 'Nome do evento', 'fontSize' => 42, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Local', 'x' => 0.28, 'y' => 0.62, 'text' => 'Local · Horário', 'fontSize' => 22, 'fill' => '#93c5fd', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
            ],
        ],
        'li_article_cover' => [
            'name' => 'Capa artigo LinkedIn',
            'description' => 'Minimalista corporativo',
            'preset' => 'li_feed',
            'group' => 'linkedin',
            'background' => ['color' => '#f8fafc', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Barra accent', 'x' => 0, 'y' => 0, 'w' => 0.012, 'h' => 1, 'fill' => '#0a66c2', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.06, 'y' => 0.35, 'text' => 'Título do artigo', 'fontSize' => 44, 'fill' => '#0f172a', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Autor', 'x' => 0.06, 'y' => 0.72, 'text' => 'Por Seu Nome · Empresa', 'fontSize' => 20, 'fill' => '#64748b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
            ],
        ],
        'web_banner_cta' => [
            'name' => 'Banner CTA web',
            'description' => 'Leaderboard com botão',
            'preset' => 'web_banner_leader',
            'group' => 'web',
            'background' => ['color' => '#0f172a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Headline', 'x' => 0.03, 'y' => 0.5, 'text' => 'Sua oferta especial', 'fontSize' => 22, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'center'],
                ['kind' => 'rect', 'name' => 'Botão', 'x' => 0.78, 'y' => 0.22, 'w' => 0.18, 'h' => 0.56, 'fill' => '#22c55e', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'CTA', 'x' => 0.87, 'y' => 0.5, 'text' => 'Saiba mais', 'fontSize' => 14, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— Instagram / Stories ——
        'ig_story_minimal' => [
            'name' => 'Story minimalista',
            'description' => 'Fundo sólido + título grande',
            'preset' => 'ig_story',
            'group' => 'instagram',
            'background' => ['color' => '#7c3aed', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.5, 'y' => 0.45, 'text' => 'NOVIDADE', 'fontSize' => 72, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Sub', 'x' => 0.5, 'y' => 0.55, 'text' => 'Deslize para cima', 'fontSize' => 28, 'fill' => '#ede9fe', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'ig_reels_hook' => [
            'name' => 'Reels gancho',
            'description' => 'Caixa amarela + Bebas no topo',
            'preset' => 'ig_reels',
            'group' => 'instagram',
            'viral' => true,
            'background' => ['color' => '#000000', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Caixa hook', 'x' => 0.04, 'y' => 0.06, 'w' => 0.92, 'h' => 0.12, 'fill' => '#fde047', 'opacity' => 100, 'rx' => 6, 'ry' => 6],
                ['kind' => 'text', 'name' => 'Hook', 'x' => 0.5, 'y' => 0.12, 'text' => 'VOCÊ SABIA DISSO?', 'fontSize' => 72, 'fill' => '#000000', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 30],
            ],
        ],
        'ig_feed_before_after' => [
            'name' => 'Feed antes/depois',
            'description' => 'Split vertical 50/50',
            'preset' => 'ig_feed_square',
            'group' => 'instagram',
            'background' => ['color' => '#18181b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Antes', 'x' => 0, 'y' => 0, 'w' => 0.5, 'h' => 1, 'fill' => '#3f3f46', 'opacity' => 100],
                ['kind' => 'rect', 'name' => 'Depois', 'x' => 0.5, 'y' => 0, 'w' => 0.5, 'h' => 1, 'fill' => '#52525b', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Antes', 'x' => 0.25, 'y' => 0.05, 'text' => 'ANTES', 'fontSize' => 36, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Depois', 'x' => 0.75, 'y' => 0.05, 'text' => 'DEPOIS', 'fontSize' => 36, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'top'],
            ],
        ],
        'ig_carousel_tip' => [
            'name' => 'Carrossel dica 1/5',
            'description' => 'Slide numerado educativo',
            'preset' => 'ig_carousel_square',
            'group' => 'instagram',
            'background' => ['color' => '#fafafa', 'opacity' => 100],
            'objects' => [
                ['kind' => 'circle', 'name' => 'Número', 'x' => 0.12, 'y' => 0.12, 'r' => 0.06, 'fill' => '#7c3aed', 'opacity' => 100],
                ['kind' => 'text', 'name' => '1', 'x' => 0.12, 'y' => 0.12, 'text' => '1', 'fontSize' => 48, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.5, 'y' => 0.42, 'text' => 'Dica #1', 'fontSize' => 56, 'fill' => '#18181b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Corpo', 'x' => 0.5, 'y' => 0.58, 'text' => 'Explique seu ponto aqui', 'fontSize' => 28, 'fill' => '#52525b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'ig_highlight_cover' => [
            'name' => 'Capa destaque IG',
            'description' => 'Círculo central + ícone',
            'preset' => 'ig_highlight',
            'group' => 'instagram',
            'background' => ['color' => '#ffffff', 'opacity' => 100],
            'objects' => [
                ['kind' => 'circle', 'name' => 'Anel', 'x' => 0.5, 'y' => 0.5, 'r' => 0.35, 'fill' => '#e4e4e7', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Label', 'x' => 0.5, 'y' => 0.5, 'text' => 'Viagens', 'fontSize' => 40, 'fill' => '#3f3f46', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— YouTube / Shorts ——
        'yt_thumb_shock' => [
            'name' => 'Thumb reação',
            'description' => 'Seta + texto enorme',
            'preset' => 'yt_thumb',
            'group' => 'youtube',
            'background' => ['color' => '#fef08a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'WOW', 'x' => 0.65, 'y' => 0.35, 'text' => 'WOW!', 'fontSize' => 120, 'fill' => '#dc2626', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'rect', 'name' => 'Barra', 'x' => 0, 'y' => 0.82, 'w' => 1, 'h' => 0.18, 'fill' => '#000000', 'opacity' => 85],
                ['kind' => 'text', 'name' => 'Sub', 'x' => 0.04, 'y' => 0.9, 'text' => 'Não acreditei nisso', 'fontSize' => 32, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'center'],
            ],
        ],
        'yt_shorts_vertical' => [
            'name' => 'Shorts título vertical',
            'description' => 'Faixa vermelha + Bebas',
            'preset' => 'yt_shorts',
            'group' => 'youtube',
            'viral' => true,
            'background' => ['color' => '#0f172a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Faixa', 'x' => 0.05, 'y' => 0.4, 'w' => 0.9, 'h' => 0.2, 'fill' => '#ef4444', 'opacity' => 95, 'rx' => 4, 'ry' => 4],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.5, 'y' => 0.5, 'text' => 'ASSISTA ATÉ O FIM', 'fontSize' => 68, 'fill' => '#ffffff', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 24],
            ],
        ],
        'yt_banner_clean' => [
            'name' => 'Banner canal clean',
            'description' => 'Nome + tagline área segura',
            'preset' => 'yt_banner_safe',
            'group' => 'youtube',
            'background' => ['color' => '#1e1b4b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Canal', 'x' => 0.5, 'y' => 0.45, 'text' => 'NOME DO CANAL', 'fontSize' => 48, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Tag', 'x' => 0.5, 'y' => 0.62, 'text' => 'Conteúdo toda semana', 'fontSize' => 22, 'fill' => '#c4b5fd', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— TikTok / Shorts genérico ——
        'tt_viral_hook' => [
            'name' => 'TikTok hook viral',
            'description' => 'Caixa amarela + Bebas — gancho no topo',
            'preset' => 'tt_video',
            'group' => 'tiktok',
            'viral' => true,
            'background' => ['color' => '#000000', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Caixa hook', 'x' => 0.04, 'y' => 0.055, 'w' => 0.92, 'h' => 0.11, 'fill' => '#fde047', 'opacity' => 100, 'rx' => 8, 'ry' => 8],
                ['kind' => 'text', 'name' => 'Hook', 'x' => 0.5, 'y' => 0.105, 'text' => 'POV: VOCÊ DESCOBRIU ISSO', 'fontSize' => 68, 'fill' => '#000000', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 20],
                ['kind' => 'rect', 'name' => 'CTA', 'x' => 0.2, 'y' => 0.88, 'w' => 0.6, 'h' => 0.06, 'fill' => '#fe2c55', 'opacity' => 100, 'rx' => 20, 'ry' => 20],
                ['kind' => 'text', 'name' => 'Seguir', 'x' => 0.5, 'y' => 0.91, 'text' => 'SEGUIR PARA MAIS', 'fontSize' => 28, 'fill' => '#ffffff', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 40],
            ],
        ],
        'tt_hook_black_box' => [
            'name' => 'TikTok caixa preta',
            'description' => 'Texto branco Bebas em caixa preta',
            'preset' => 'tt_video',
            'group' => 'tiktok',
            'viral' => true,
            'background' => ['color' => '#18181b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Hook', 'x' => 0.5, 'y' => 0.14, 'text' => 'NINGUÉM TE CONTOU ISSO', 'fontSize' => 64, 'fill' => '#ffffff', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 24, 'textBackground' => ['fill' => '#000000', 'opacity' => 92, 'padX' => 20, 'padY' => 14, 'rx' => 8]],
            ],
        ],
        'short_announce' => [
            'name' => 'Short anúncio',
            'description' => 'Vertical lançamento + Bebas',
            'preset' => 'short_9_16',
            'group' => 'shorts',
            'viral' => true,
            'background' => ['color' => '#059669', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Novo', 'x' => 0.5, 'y' => 0.35, 'text' => 'LANÇAMENTO', 'fontSize' => 88, 'fill' => '#ffffff', 'fontSlug' => 'bebas_neue', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center', 'charSpacing' => 50, 'shadow' => true, 'shadowBlur' => 16],
                ['kind' => 'text', 'name' => 'Data', 'x' => 0.5, 'y' => 0.48, 'text' => '15 · JUL · 2026', 'fontSize' => 32, 'fill' => '#d1fae5', 'fontSlug' => 'montserrat', 'originX' => 'center', 'originY' => 'center', 'textAlign' => 'center'],
            ],
        ],
        // —— Facebook / LinkedIn ——
        'fb_ad_offer' => [
            'name' => 'Anúncio FB oferta',
            'description' => 'Split cor + CTA',
            'preset' => 'fb_ad_landscape',
            'group' => 'facebook',
            'background' => ['color' => '#ffffff', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Lado A', 'x' => 0, 'y' => 0, 'w' => 0.55, 'h' => 1, 'fill' => '#2563eb', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Oferta', 'x' => 0.75, 'y' => 0.4, 'text' => '50% OFF', 'fontSize' => 56, 'fill' => '#1e3a8a', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'CTA', 'x' => 0.75, 'y' => 0.62, 'text' => 'Compre agora →', 'fontSize' => 24, 'fill' => '#3b82f6', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'li_hiring' => [
            'name' => 'LinkedIn vagas',
            'description' => 'Estamos contratando',
            'preset' => 'li_feed',
            'group' => 'linkedin',
            'background' => ['color' => '#0a66c2', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.5, 'y' => 0.38, 'text' => 'ESTAMOS CONTRATANDO', 'fontSize' => 48, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Cargo', 'x' => 0.5, 'y' => 0.58, 'text' => 'Desenvolvedor(a) · Remoto', 'fontSize' => 26, 'fill' => '#bfdbfe', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— Avatares ——
        'avatar_circle_frame' => [
            'name' => 'Avatar com anel',
            'description' => 'Círculo central para foto',
            'preset' => 'avatar_lg',
            'group' => 'avatars',
            'background' => ['color' => '#27272a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'circle', 'name' => 'Foto', 'x' => 0.5, 'y' => 0.5, 'r' => 0.38, 'fill' => '#52525b', 'opacity' => 100],
                ['kind' => 'circle', 'name' => 'Anel', 'x' => 0.5, 'y' => 0.5, 'r' => 0.42, 'fill' => 'transparent', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Iniciais', 'x' => 0.5, 'y' => 0.5, 'text' => 'AB', 'fontSize' => 120, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'avatar_yt_channel' => [
            'name' => 'Avatar canal YouTube',
            'description' => 'Iniciais + gradiente simulado',
            'preset' => 'avatar_xl',
            'group' => 'avatars',
            'background' => ['color' => '#7c3aed', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Faixa', 'x' => 0, 'y' => 0.75, 'w' => 1, 'h' => 0.25, 'fill' => '#5b21b6', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Iniciais', 'x' => 0.5, 'y' => 0.42, 'text' => 'CS', 'fontSize' => 180, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— Marketing / impressos ——
        'mkt_flyer_sale' => [
            'name' => 'Panfleto promo A5',
            'description' => 'Grande desconto central',
            'preset' => 'mkt_flyer_a5',
            'group' => 'marketing',
            'background' => ['color' => '#fef2f2', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Header', 'x' => 0, 'y' => 0, 'w' => 1, 'h' => 0.18, 'fill' => '#dc2626', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Mega', 'x' => 0.5, 'y' => 0.45, 'text' => 'MEGA\nSALE', 'fontSize' => 96, 'fill' => '#991b1b', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Detalhe', 'x' => 0.5, 'y' => 0.72, 'text' => 'Válido até domingo', 'fontSize' => 32, 'fill' => '#7f1d1d', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'mkt_card_modern' => [
            'name' => 'Cartão visita moderno',
            'description' => 'Nome + contato lateral',
            'preset' => 'mkt_card_visit_br',
            'group' => 'marketing',
            'background' => ['color' => '#0f172a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Accent', 'x' => 0, 'y' => 0, 'w' => 0.04, 'h' => 1, 'fill' => '#22d3ee', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Nome', 'x' => 0.1, 'y' => 0.35, 'text' => 'Seu Nome', 'fontSize' => 36, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Cargo', 'x' => 0.1, 'y' => 0.52, 'text' => 'Designer · Empresa', 'fontSize' => 18, 'fill' => '#94a3b8', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Contato', 'x' => 0.1, 'y' => 0.72, 'text' => 'email@site.com · (11) 99999', 'fontSize' => 14, 'fill' => '#64748b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
            ],
        ],
        'mkt_folder_tri' => [
            'name' => 'Folder tri-fold capa',
            'description' => 'Três colunas guia',
            'preset' => 'mkt_folder_a4_trifold',
            'group' => 'marketing',
            'background' => ['color' => '#ffffff', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Col 1', 'x' => 0, 'y' => 0, 'w' => 0.333, 'h' => 1, 'fill' => '#f4f4f5', 'opacity' => 100],
                ['kind' => 'rect', 'name' => 'Col 2', 'x' => 0.333, 'y' => 0, 'w' => 0.334, 'h' => 1, 'fill' => '#e4e4e7', 'opacity' => 100],
                ['kind' => 'rect', 'name' => 'Col 3', 'x' => 0.667, 'y' => 0, 'w' => 0.333, 'h' => 1, 'fill' => '#f4f4f5', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Marca', 'x' => 0.5, 'y' => 0.4, 'text' => 'SUA MARCA', 'fontSize' => 64, 'fill' => '#18181b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'mkt_invite_wedding' => [
            'name' => 'Convite elegante',
            'description' => 'Casamento / evento formal',
            'preset' => 'mkt_invite_10x15',
            'group' => 'marketing',
            'background' => ['color' => '#fffbeb', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.5, 'y' => 0.32, 'text' => 'Save the Date', 'fontSize' => 40, 'fill' => '#92400e', 'fontFamily' => 'Georgia, serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Nomes', 'x' => 0.5, 'y' => 0.48, 'text' => 'Ana & Bruno', 'fontSize' => 56, 'fill' => '#78350f', 'fontFamily' => 'Georgia, serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Data', 'x' => 0.5, 'y' => 0.65, 'text' => '12 · Outubro · 2026', 'fontSize' => 24, 'fill' => '#a16207', 'fontFamily' => 'Georgia, serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        // —— Web / banners ——
        'web_hero_saas' => [
            'name' => 'Hero SaaS',
            'description' => 'Headline + subtítulo centro',
            'preset' => 'web_hero',
            'group' => 'web',
            'background' => ['color' => '#020617', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Headline', 'x' => 0.5, 'y' => 0.38, 'text' => 'Cresça seu negócio online', 'fontSize' => 56, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Sub', 'x' => 0.5, 'y' => 0.58, 'text' => 'Plataforma completa para equipes', 'fontSize' => 24, 'fill' => '#94a3b8', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'rect', 'name' => 'CTA', 'x' => 0.42, 'y' => 0.7, 'w' => 0.16, 'h' => 0.12, 'fill' => '#6366f1', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'CTA txt', 'x' => 0.5, 'y' => 0.76, 'text' => 'Começar grátis', 'fontSize' => 18, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'web_og_blog' => [
            'name' => 'Open Graph artigo',
            'description' => 'Blog / SEO share',
            'preset' => 'web_og',
            'group' => 'web',
            'background' => ['color' => '#1e293b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Accent', 'x' => 0, 'y' => 0, 'w' => 0.008, 'h' => 1, 'fill' => '#38bdf8', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.06, 'y' => 0.35, 'text' => 'Título do artigo para SEO', 'fontSize' => 42, 'fill' => '#f8fafc', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
                ['kind' => 'text', 'name' => 'Site', 'x' => 0.06, 'y' => 0.72, 'text' => 'seusite.com.br', 'fontSize' => 20, 'fill' => '#64748b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'top'],
            ],
        ],
        'pin_product' => [
            'name' => 'Pin produto Pinterest',
            'description' => 'Título + preço base',
            'preset' => 'pin_standard',
            'group' => 'pinterest',
            'background' => ['color' => '#fafafa', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Foto area', 'x' => 0.05, 'y' => 0.05, 'w' => 0.9, 'h' => 0.65, 'fill' => '#e4e4e7', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Produto', 'x' => 0.5, 'y' => 0.78, 'text' => 'Nome do produto', 'fontSize' => 32, 'fill' => '#18181b', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Preço', 'x' => 0.5, 'y' => 0.88, 'text' => 'R$ 99,90', 'fontSize' => 28, 'fill' => '#dc2626', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'wa_status_promo' => [
            'name' => 'Status WhatsApp promo',
            'description' => 'Oferta vertical rápida',
            'preset' => 'wa_status',
            'group' => 'whatsapp',
            'background' => ['color' => '#14532d', 'opacity' => 100],
            'objects' => [
                ['kind' => 'text', 'name' => 'Promo', 'x' => 0.5, 'y' => 0.4, 'text' => 'OFERTA\nHOJE', 'fontSize' => 72, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'center', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Chame', 'x' => 0.5, 'y' => 0.88, 'text' => 'Responda este status', 'fontSize' => 24, 'fill' => '#bbf7d0', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'x_post_news' => [
            'name' => 'Post X notícia',
            'description' => 'Breaking news estilo',
            'preset' => 'x_post',
            'group' => 'twitter',
            'background' => ['color' => '#18181b', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Alert', 'x' => 0, 'y' => 0, 'w' => 1, 'h' => 0.15, 'fill' => '#dc2626', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Breaking', 'x' => 0.04, 'y' => 0.075, 'text' => 'URGENTE', 'fontSize' => 32, 'fill' => '#ffffff', 'fontFamily' => 'Impact, Arial Black, sans-serif', 'originX' => 'left', 'originY' => 'center'],
                ['kind' => 'text', 'name' => 'Headline', 'x' => 0.04, 'y' => 0.55, 'text' => 'Manchete principal aqui', 'fontSize' => 48, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'center'],
            ],
        ],
        'ratio_portrait_photo' => [
            'name' => 'Retrato foto 3:4',
            'description' => 'Moldura clara para foto',
            'preset' => 'ratio_3_4',
            'group' => 'ratios',
            'background' => ['color' => '#f4f4f5', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Área foto', 'x' => 0.08, 'y' => 0.06, 'w' => 0.84, 'h' => 0.72, 'fill' => '#d4d4d8', 'opacity' => 100],
                ['kind' => 'text', 'name' => 'Legenda', 'x' => 0.5, 'y' => 0.88, 'text' => 'Legenda da foto', 'fontSize' => 28, 'fill' => '#52525b', 'fontFamily' => 'Georgia, serif', 'originX' => 'center', 'originY' => 'center'],
            ],
        ],
        'ratio_landscape_photo' => [
            'name' => 'Paisagem foto 16:9',
            'description' => 'Faixa título inferior',
            'preset' => 'ratio_16_9',
            'group' => 'ratios',
            'background' => ['color' => '#27272a', 'opacity' => 100],
            'objects' => [
                ['kind' => 'rect', 'name' => 'Barra', 'x' => 0, 'y' => 0.78, 'w' => 1, 'h' => 0.22, 'fill' => '#000000', 'opacity' => 70],
                ['kind' => 'text', 'name' => 'Título', 'x' => 0.04, 'y' => 0.88, 'text' => 'Título da imagem', 'fontSize' => 36, 'fill' => '#ffffff', 'fontFamily' => 'Arial, sans-serif', 'originX' => 'left', 'originY' => 'center'],
            ],
        ],
    ],

    'element_groups' => [],

    'elements' => [],

    'frame_presets' => [
        'thin_white' => ['name' => 'Fina branca', 'category' => 'basico'],
        'thick_solid' => ['name' => 'Borda grossa', 'category' => 'basico'],
        'double_line' => ['name' => 'Linha dupla', 'category' => 'basico'],
        'rounded_modern' => ['name' => 'Cantos arredondados', 'category' => 'moderno'],
        'gradient_border' => ['name' => 'Borda degradê', 'category' => 'moderno'],
        'neon_solid' => ['name' => 'Neon glow', 'category' => 'neon'],
        'letterbox_frame' => ['name' => 'Letterbox cinema', 'category' => 'cinema'],
        'polaroid' => ['name' => 'Polaroid', 'category' => 'vintage'],
        'instagram_round' => ['name' => 'Anel Instagram', 'category' => 'social'],
        'youtube_red' => ['name' => 'Accent YouTube', 'category' => 'social'],
        'corner_brackets' => ['name' => 'Cantoneiras', 'category' => 'tech'],
        'gold_classic' => ['name' => 'Dourado duplo', 'category' => 'luxo'],
    ],

    'defaults' => [
        'preset' => 'custom',
        'width' => 1920,
        'height' => 1080,
        'background_color' => '#ffffff',
        'background_opacity' => 100,
    ],

    /** Botões principais acima do canvas — sempre visíveis */
    'primary_formats' => [
        ['slug' => 'yt_thumb_hd', 'label' => 'YouTube Full HD', 'aspect' => '16:9'],
        ['slug' => 'yt_thumb', 'label' => 'YouTube Thumbnail', 'aspect' => '16:9'],
        ['slug' => 'yt_shorts', 'label' => 'YouTube Shorts', 'aspect' => '9:16'],
        ['slug' => 'ig_feed_square', 'label' => 'Instagram 1:1', 'aspect' => '1:1'],
        ['slug' => 'ig_story', 'label' => 'Story / Reels', 'aspect' => '9:16'],
        ['slug' => 'tt_video', 'label' => 'TikTok', 'aspect' => '9:16'],
        ['slug' => 'ratio_16_9_hd', 'label' => 'Paisagem 16:9', 'aspect' => '16:9'],
    ],

    /** Ordem dos grupos na lista lateral */
    'group_order' => [
        'YouTube',
        'Proporções genéricas',
        'Shorts / Reels / vertical',
        'Instagram',
        'TikTok',
        'Facebook',
        'LinkedIn',
        'X / Twitter',
        'Pinterest',
        'WhatsApp',
        'Sites & banners',
        'Stories / vertical',
        'Avatares & perfis (circular)',
        'Panfletos, folders & cartões',
        'Impressão',
    ],

    /** Formato Image Studio → plataforma do módulo Thumbnail */
    'preset_platform_map' => [
        'custom' => 'youtube_landscape',
        'yt_thumb' => 'youtube_landscape',
        'yt_thumb_hd' => 'youtube_landscape',
        'yt_thumb_4k' => 'youtube_landscape',
        'yt_community_wide' => 'youtube_landscape',
        'yt_shorts' => 'youtube_shorts',
        'yt_shorts_thumb' => 'youtube_shorts',
        'ig_feed_square' => 'instagram_feed_square',
        'ig_carousel_square' => 'instagram_feed_square',
        'ig_reels' => 'instagram_reels',
        'ig_reels_cover_sq' => 'instagram_reels',
        'ig_story' => 'instagram_stories',
        'tiktok_cover' => 'tiktok',
        'tiktok_vertical' => 'tiktok',
    ],
];
