<?php

return [
    'groups' => [
        'system' => 'Sistema (Windows)',
        'google_display' => 'Display & impacto (Google)',
        'google_sans' => 'Sans-serif (Google)',
        'google_serif' => 'Serif & editorial (Google)',
        'google_script' => 'Script & manuscrito (Google)',
        'google_mono' => 'Monoespaçada (Google)',
        'icons_fa' => 'Ícones — Font Awesome',
        'icons_material' => 'Ícones — Material Symbols',
    ],

    /*
    | Fontes web (Google Fonts). family = nome CSS; italic = suporta itálico.
    */
    'google_fonts' => [
        ['slug' => 'bebas_neue', 'label' => 'Bebas Neue', 'group' => 'google_display', 'family' => 'Bebas Neue', 'weights' => [400], 'italic' => false],
        ['slug' => 'anton', 'label' => 'Anton', 'group' => 'google_display', 'family' => 'Anton', 'weights' => [400], 'italic' => false],
        ['slug' => 'oswald', 'label' => 'Oswald', 'group' => 'google_display', 'family' => 'Oswald', 'weights' => [400, 500, 600, 700], 'italic' => false],
        ['slug' => 'bangers', 'label' => 'Bangers', 'group' => 'google_display', 'family' => 'Bangers', 'weights' => [400], 'italic' => false],
        ['slug' => 'archivo_black', 'label' => 'Archivo Black', 'group' => 'google_display', 'family' => 'Archivo Black', 'weights' => [400], 'italic' => false],
        ['slug' => 'black_ops_one', 'label' => 'Black Ops One', 'group' => 'google_display', 'family' => 'Black Ops One', 'weights' => [400], 'italic' => false],
        ['slug' => 'bungee', 'label' => 'Bungee', 'group' => 'google_display', 'family' => 'Bungee', 'weights' => [400], 'italic' => false],
        ['slug' => 'russo_one', 'label' => 'Russo One', 'group' => 'google_display', 'family' => 'Russo One', 'weights' => [400], 'italic' => false],
        ['slug' => 'alfa_slab_one', 'label' => 'Alfa Slab One', 'group' => 'google_display', 'family' => 'Alfa Slab One', 'weights' => [400], 'italic' => false],
        ['slug' => 'righteous', 'label' => 'Righteous', 'group' => 'google_display', 'family' => 'Righteous', 'weights' => [400], 'italic' => false],
        ['slug' => 'teko', 'label' => 'Teko', 'group' => 'google_display', 'family' => 'Teko', 'weights' => [400, 500, 600, 700], 'italic' => false],
        ['slug' => 'saira_condensed', 'label' => 'Saira Condensed', 'group' => 'google_display', 'family' => 'Saira Condensed', 'weights' => [400, 600, 700, 900], 'italic' => false],
        ['slug' => 'abril_fatface', 'label' => 'Abril Fatface', 'group' => 'google_display', 'family' => 'Abril Fatface', 'weights' => [400], 'italic' => false],
        ['slug' => 'orbitron', 'label' => 'Orbitron', 'group' => 'google_display', 'family' => 'Orbitron', 'weights' => [400, 500, 600, 700, 900], 'italic' => false],
        ['slug' => 'press_start_2p', 'label' => 'Press Start 2P', 'group' => 'google_display', 'family' => 'Press Start 2P', 'weights' => [400], 'italic' => false],

        ['slug' => 'roboto', 'label' => 'Roboto', 'group' => 'google_sans', 'family' => 'Roboto', 'weights' => [400, 500, 700, 900], 'italic' => true],
        ['slug' => 'open_sans', 'label' => 'Open Sans', 'group' => 'google_sans', 'family' => 'Open Sans', 'weights' => [400, 600, 700, 800], 'italic' => true],
        ['slug' => 'montserrat', 'label' => 'Montserrat', 'group' => 'google_sans', 'family' => 'Montserrat', 'weights' => [400, 500, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'poppins', 'label' => 'Poppins', 'group' => 'google_sans', 'family' => 'Poppins', 'weights' => [400, 500, 600, 700, 800], 'italic' => true],
        ['slug' => 'lato', 'label' => 'Lato', 'group' => 'google_sans', 'family' => 'Lato', 'weights' => [400, 700, 900], 'italic' => true],
        ['slug' => 'raleway', 'label' => 'Raleway', 'group' => 'google_sans', 'family' => 'Raleway', 'weights' => [400, 600, 700, 800], 'italic' => true],
        ['slug' => 'nunito', 'label' => 'Nunito', 'group' => 'google_sans', 'family' => 'Nunito', 'weights' => [400, 600, 700, 800], 'italic' => true],
        ['slug' => 'ubuntu', 'label' => 'Ubuntu', 'group' => 'google_sans', 'family' => 'Ubuntu', 'weights' => [400, 500, 700], 'italic' => true],
        ['slug' => 'rubik', 'label' => 'Rubik', 'group' => 'google_sans', 'family' => 'Rubik', 'weights' => [400, 500, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'inter', 'label' => 'Inter', 'group' => 'google_sans', 'family' => 'Inter', 'weights' => [400, 500, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'work_sans', 'label' => 'Work Sans', 'group' => 'google_sans', 'family' => 'Work Sans', 'weights' => [400, 500, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'dm_sans', 'label' => 'DM Sans', 'group' => 'google_sans', 'family' => 'DM Sans', 'weights' => [400, 500, 700], 'italic' => true],
        ['slug' => 'space_grotesk', 'label' => 'Space Grotesk', 'group' => 'google_sans', 'family' => 'Space Grotesk', 'weights' => [400, 500, 600, 700], 'italic' => false],
        ['slug' => 'barlow_condensed', 'label' => 'Barlow Condensed', 'group' => 'google_sans', 'family' => 'Barlow Condensed', 'weights' => [400, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'exo_2', 'label' => 'Exo 2', 'group' => 'google_sans', 'family' => 'Exo 2', 'weights' => [400, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'kanit', 'label' => 'Kanit', 'group' => 'google_sans', 'family' => 'Kanit', 'weights' => [400, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'comfortaa', 'label' => 'Comfortaa', 'group' => 'google_sans', 'family' => 'Comfortaa', 'weights' => [400, 600, 700], 'italic' => false],
        ['slug' => 'quicksand', 'label' => 'Quicksand', 'group' => 'google_sans', 'family' => 'Quicksand', 'weights' => [400, 500, 600, 700], 'italic' => false],
        ['slug' => 'josefin_sans', 'label' => 'Josefin Sans', 'group' => 'google_sans', 'family' => 'Josefin Sans', 'weights' => [400, 600, 700], 'italic' => true],
        ['slug' => 'source_sans_3', 'label' => 'Source Sans 3', 'group' => 'google_sans', 'family' => 'Source Sans 3', 'weights' => [400, 600, 700, 900], 'italic' => true],
        ['slug' => 'fira_sans', 'label' => 'Fira Sans', 'group' => 'google_sans', 'family' => 'Fira Sans', 'weights' => [400, 600, 700, 800, 900], 'italic' => true],

        ['slug' => 'playfair_display', 'label' => 'Playfair Display', 'group' => 'google_serif', 'family' => 'Playfair Display', 'weights' => [400, 600, 700, 800, 900], 'italic' => true],
        ['slug' => 'merriweather', 'label' => 'Merriweather', 'group' => 'google_serif', 'family' => 'Merriweather', 'weights' => [400, 700, 900], 'italic' => true],
        ['slug' => 'libre_baskerville', 'label' => 'Libre Baskerville', 'group' => 'google_serif', 'family' => 'Libre Baskerville', 'weights' => [400, 700], 'italic' => true],
        ['slug' => 'lora', 'label' => 'Lora', 'group' => 'google_serif', 'family' => 'Lora', 'weights' => [400, 500, 600, 700], 'italic' => true],
        ['slug' => 'cinzel', 'label' => 'Cinzel', 'group' => 'google_serif', 'family' => 'Cinzel', 'weights' => [400, 600, 700, 900], 'italic' => false],
        ['slug' => 'crimson_text', 'label' => 'Crimson Text', 'group' => 'google_serif', 'family' => 'Crimson Text', 'weights' => [400, 600, 700], 'italic' => true],

        ['slug' => 'pacifico', 'label' => 'Pacifico', 'group' => 'google_script', 'family' => 'Pacifico', 'weights' => [400], 'italic' => false],
        ['slug' => 'lobster', 'label' => 'Lobster', 'group' => 'google_script', 'family' => 'Lobster', 'weights' => [400], 'italic' => false],
        ['slug' => 'permanent_marker', 'label' => 'Permanent Marker', 'group' => 'google_script', 'family' => 'Permanent Marker', 'weights' => [400], 'italic' => false],
        ['slug' => 'great_vibes', 'label' => 'Great Vibes', 'group' => 'google_script', 'family' => 'Great Vibes', 'weights' => [400], 'italic' => false],
        ['slug' => 'satisfy', 'label' => 'Satisfy', 'group' => 'google_script', 'family' => 'Satisfy', 'weights' => [400], 'italic' => false],
        ['slug' => 'caveat', 'label' => 'Caveat', 'group' => 'google_script', 'family' => 'Caveat', 'weights' => [400, 600, 700], 'italic' => false],
        ['slug' => 'dancing_script', 'label' => 'Dancing Script', 'group' => 'google_script', 'family' => 'Dancing Script', 'weights' => [400, 600, 700], 'italic' => false],

        ['slug' => 'roboto_mono', 'label' => 'Roboto Mono', 'group' => 'google_mono', 'family' => 'Roboto Mono', 'weights' => [400, 600, 700], 'italic' => true],
        ['slug' => 'fira_code', 'label' => 'Fira Code', 'group' => 'google_mono', 'family' => 'Fira Code', 'weights' => [400, 600, 700], 'italic' => false],
        ['slug' => 'jetbrains_mono', 'label' => 'JetBrains Mono', 'group' => 'google_mono', 'family' => 'JetBrains Mono', 'weights' => [400, 600, 700, 800], 'italic' => true],
    ],

    'icon_fonts' => [
        [
            'slug' => 'fa_solid',
            'label' => 'Font Awesome Solid',
            'group' => 'icons_fa',
            'source' => 'cdn',
            'css' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
            'family' => '"Font Awesome 6 Free"',
            'weight' => 900,
            'italic' => false,
        ],
        [
            'slug' => 'fa_regular',
            'label' => 'Font Awesome Regular',
            'group' => 'icons_fa',
            'source' => 'cdn',
            'css' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
            'family' => '"Font Awesome 6 Free"',
            'weight' => 400,
            'italic' => false,
        ],
        [
            'slug' => 'fa_brands',
            'label' => 'Font Awesome Brands',
            'group' => 'icons_fa',
            'source' => 'cdn',
            'css' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
            'family' => '"Font Awesome 6 Brands"',
            'weight' => 400,
            'italic' => false,
        ],
        [
            'slug' => 'material_symbols',
            'label' => 'Material Symbols',
            'group' => 'icons_material',
            'source' => 'cdn',
            'css' => 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0',
            'family' => '"Material Symbols Outlined"',
            'weight' => 400,
            'italic' => false,
            'material' => true,
        ],
    ],

    'icon_glyphs' => [
        // Font Awesome Solid
        ['slug' => 'fa_star', 'label' => 'Estrela', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f005}"],
        ['slug' => 'fa_heart', 'label' => 'Coração', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f004}"],
        ['slug' => 'fa_bolt', 'label' => 'Raio', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f0e7}"],
        ['slug' => 'fa_fire', 'label' => 'Fogo', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f06d}"],
        ['slug' => 'fa_crown', 'label' => 'Coroa', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f521}"],
        ['slug' => 'fa_trophy', 'label' => 'Troféu', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f091}"],
        ['slug' => 'fa_check', 'label' => 'Check', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f00c}"],
        ['slug' => 'fa_xmark', 'label' => 'X', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{f00d}"],
        ['slug' => 'fa_plus', 'label' => 'Mais', 'group' => 'Símbolos', 'font' => 'fa_solid', 'char' => "\u{2b}"],
        ['slug' => 'fa_play', 'label' => 'Play', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f04b}"],
        ['slug' => 'fa_pause', 'label' => 'Pause', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f04c}"],
        ['slug' => 'fa_music', 'label' => 'Música', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f001}"],
        ['slug' => 'fa_video', 'label' => 'Vídeo', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f03d}"],
        ['slug' => 'fa_camera', 'label' => 'Câmera', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f030}"],
        ['slug' => 'fa_image', 'label' => 'Imagem', 'group' => 'Mídia', 'font' => 'fa_solid', 'char' => "\u{f03e}"],
        ['slug' => 'fa_thumbs_up', 'label' => 'Like', 'group' => 'Social', 'font' => 'fa_solid', 'char' => "\u{f164}"],
        ['slug' => 'fa_comment', 'label' => 'Comentário', 'group' => 'Social', 'font' => 'fa_solid', 'char' => "\u{f075}"],
        ['slug' => 'fa_share', 'label' => 'Compartilhar', 'group' => 'Social', 'font' => 'fa_solid', 'char' => "\u{f064}"],
        ['slug' => 'fa_hashtag', 'label' => 'Hashtag', 'group' => 'Social', 'font' => 'fa_solid', 'char' => "\u{23}"],
        ['slug' => 'fa_at', 'label' => 'Arroba', 'group' => 'Social', 'font' => 'fa_solid', 'char' => "\u{40}"],
        ['slug' => 'fa_user', 'label' => 'Usuário', 'group' => 'Pessoas', 'font' => 'fa_solid', 'char' => "\u{f007}"],
        ['slug' => 'fa_users', 'label' => 'Grupo', 'group' => 'Pessoas', 'font' => 'fa_solid', 'char' => "\u{f0c0}"],
        ['slug' => 'fa_bell', 'label' => 'Sino', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f0f3}"],
        ['slug' => 'fa_bookmark', 'label' => 'Salvar', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f02e}"],
        ['slug' => 'fa_cart', 'label' => 'Carrinho', 'group' => 'Comércio', 'font' => 'fa_solid', 'char' => "\u{f07a}"],
        ['slug' => 'fa_gift', 'label' => 'Presente', 'group' => 'Comércio', 'font' => 'fa_solid', 'char' => "\u{f06b}"],
        ['slug' => 'fa_rocket', 'label' => 'Foguete', 'group' => 'Tech', 'font' => 'fa_solid', 'char' => "\u{f135}"],
        ['slug' => 'fa_globe', 'label' => 'Globo', 'group' => 'Tech', 'font' => 'fa_solid', 'char' => "\u{f0ac}"],
        ['slug' => 'fa_wifi', 'label' => 'Wi‑Fi', 'group' => 'Tech', 'font' => 'fa_solid', 'char' => "\u{f1eb}"],
        ['slug' => 'fa_lock', 'label' => 'Cadeado', 'group' => 'Tech', 'font' => 'fa_solid', 'char' => "\u{f023}"],
        ['slug' => 'fa_shield', 'label' => 'Escudo', 'group' => 'Tech', 'font' => 'fa_solid', 'char' => "\u{f132}"],
        ['slug' => 'fa_warning', 'label' => 'Alerta', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f071}"],
        ['slug' => 'fa_info', 'label' => 'Info', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f129}"],
        ['slug' => 'fa_home', 'label' => 'Home', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f015}"],
        ['slug' => 'fa_search', 'label' => 'Busca', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f002}"],
        ['slug' => 'fa_gear', 'label' => 'Config', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f013}"],
        ['slug' => 'fa_palette', 'label' => 'Paleta', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f53f}"],
        ['slug' => 'fa_pen', 'label' => 'Caneta', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f304}"],
        ['slug' => 'fa_trash', 'label' => 'Lixeira', 'group' => 'UI', 'font' => 'fa_solid', 'char' => "\u{f1f8}"],
        ['slug' => 'fa_arrow_right', 'label' => 'Seta →', 'group' => 'Setas', 'font' => 'fa_solid', 'char' => "\u{f061}"],
        ['slug' => 'fa_arrow_left', 'label' => 'Seta ←', 'group' => 'Setas', 'font' => 'fa_solid', 'char' => "\u{f060}"],
        ['slug' => 'fa_sun', 'label' => 'Sol', 'group' => 'Natureza', 'font' => 'fa_solid', 'char' => "\u{f185}"],
        ['slug' => 'fa_moon', 'label' => 'Lua', 'group' => 'Natureza', 'font' => 'fa_solid', 'char' => "\u{f186}"],
        // Font Awesome Brands
        ['slug' => 'fa_youtube', 'label' => 'YouTube', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f167}"],
        ['slug' => 'fa_instagram', 'label' => 'Instagram', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f16d}"],
        ['slug' => 'fa_tiktok', 'label' => 'TikTok', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{e07b}"],
        ['slug' => 'fa_facebook', 'label' => 'Facebook', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f09a}"],
        ['slug' => 'fa_twitter', 'label' => 'X / Twitter', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f099}"],
        ['slug' => 'fa_whatsapp', 'label' => 'WhatsApp', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f232}"],
        ['slug' => 'fa_spotify', 'label' => 'Spotify', 'group' => 'Redes', 'font' => 'fa_brands', 'char' => "\u{f1bc}"],
        // Material Symbols (ligature = nome do ícone)
        ['slug' => 'mat_favorite', 'label' => 'Favorito', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'favorite'],
        ['slug' => 'mat_star', 'label' => 'Estrela', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'star'],
        ['slug' => 'mat_bolt', 'label' => 'Raio', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'bolt'],
        ['slug' => 'mat_shopping_cart', 'label' => 'Carrinho', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'shopping_cart'],
        ['slug' => 'mat_play_circle', 'label' => 'Play', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'play_circle'],
        ['slug' => 'mat_photo_camera', 'label' => 'Câmera', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'photo_camera'],
        ['slug' => 'mat_videocam', 'label' => 'Vídeo', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'videocam'],
        ['slug' => 'mat_music_note', 'label' => 'Música', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'music_note'],
        ['slug' => 'mat_rocket_launch', 'label' => 'Foguete', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'rocket_launch'],
        ['slug' => 'mat_celebration', 'label' => 'Celebração', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'celebration'],
        ['slug' => 'mat_trending_up', 'label' => 'Trending', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'trending_up'],
        ['slug' => 'mat_campaign', 'label' => 'Megafone', 'group' => 'Material', 'font' => 'material_symbols', 'char' => 'campaign'],
    ],
];
