<?php

/**
 * Ícones Bootstrap Icons (MIT) — gerado por scripts/sync-bootstrap-icons.mjs
 * Não edite manualmente; rode: node scripts/sync-bootstrap-icons.mjs
 */
return [
    'groups' => [
    'bs_social' => 'Social & marcas',
    'bs_media' => 'Mídia & áudio',
    'bs_communication' => 'Comunicação',
    'bs_commerce' => 'Comércio',
    'bs_ui' => 'Interface',
    'bs_arrows' => 'Setas',
    'bs_people' => 'Pessoas',
    'bs_files' => 'Arquivos',
    'bs_tech' => 'Tech',
    'bs_location' => 'Local & tempo',
    'bs_creative' => 'Criativo',
    'bs_security' => 'Segurança',
],

    'elements' => [
    [
        'slug' => 'bs_instagram',
        'name' => 'Instagram',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'instagram',
        'icon_url' => '/icons/bootstrap/instagram.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_facebook',
        'name' => 'Facebook',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'facebook',
        'icon_url' => '/icons/bootstrap/facebook.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_twitter_x',
        'name' => 'X / Twitter',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'twitter-x',
        'icon_url' => '/icons/bootstrap/twitter-x.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_youtube',
        'name' => 'YouTube',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'youtube',
        'icon_url' => '/icons/bootstrap/youtube.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_tiktok',
        'name' => 'TikTok',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'tiktok',
        'icon_url' => '/icons/bootstrap/tiktok.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_whatsapp',
        'name' => 'WhatsApp',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'whatsapp',
        'icon_url' => '/icons/bootstrap/whatsapp.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_linkedin',
        'name' => 'LinkedIn',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'linkedin',
        'icon_url' => '/icons/bootstrap/linkedin.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_telegram',
        'name' => 'Telegram',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'telegram',
        'icon_url' => '/icons/bootstrap/telegram.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_heart',
        'name' => 'Coração',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'heart',
        'icon_url' => '/icons/bootstrap/heart.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_heart_fill',
        'name' => 'Coração preenchido',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'heart-fill',
        'icon_url' => '/icons/bootstrap/heart-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_star',
        'name' => 'Estrela',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'star',
        'icon_url' => '/icons/bootstrap/star.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_star_fill',
        'name' => 'Estrela preenchida',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'star-fill',
        'icon_url' => '/icons/bootstrap/star-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bookmark',
        'name' => 'Salvar',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bookmark',
        'icon_url' => '/icons/bootstrap/bookmark.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bookmark_fill',
        'name' => 'Salvo',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bookmark-fill',
        'icon_url' => '/icons/bootstrap/bookmark-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_share',
        'name' => 'Compartilhar',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'share',
        'icon_url' => '/icons/bootstrap/share.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_share_fill',
        'name' => 'Compartilhar fill',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'share-fill',
        'icon_url' => '/icons/bootstrap/share-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_hand_thumbs_up',
        'name' => 'Curtir',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'hand-thumbs-up',
        'icon_url' => '/icons/bootstrap/hand-thumbs-up.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_hand_thumbs_up_fill',
        'name' => 'Curtir fill',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'hand-thumbs-up-fill',
        'icon_url' => '/icons/bootstrap/hand-thumbs-up-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_emoji_smile',
        'name' => 'Emoji',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'emoji-smile',
        'icon_url' => '/icons/bootstrap/emoji-smile.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_emoji_heart_eyes',
        'name' => 'Emoji amor',
        'group' => 'bs_social',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'emoji-heart-eyes',
        'icon_url' => '/icons/bootstrap/emoji-heart-eyes.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_play_fill',
        'name' => 'Play',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'play-fill',
        'icon_url' => '/icons/bootstrap/play-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_pause_fill',
        'name' => 'Pause',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'pause-fill',
        'icon_url' => '/icons/bootstrap/pause-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_stop_fill',
        'name' => 'Stop',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'stop-fill',
        'icon_url' => '/icons/bootstrap/stop-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_skip_forward_fill',
        'name' => 'Avançar',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'skip-forward-fill',
        'icon_url' => '/icons/bootstrap/skip-forward-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_skip_backward_fill',
        'name' => 'Voltar',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'skip-backward-fill',
        'icon_url' => '/icons/bootstrap/skip-backward-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_camera',
        'name' => 'Câmera',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'camera',
        'icon_url' => '/icons/bootstrap/camera.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_camera_fill',
        'name' => 'Câmera fill',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'camera-fill',
        'icon_url' => '/icons/bootstrap/camera-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_image',
        'name' => 'Imagem',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'image',
        'icon_url' => '/icons/bootstrap/image.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_image_fill',
        'name' => 'Imagem fill',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'image-fill',
        'icon_url' => '/icons/bootstrap/image-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_film',
        'name' => 'Filme',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'film',
        'icon_url' => '/icons/bootstrap/film.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_music_note_beamed',
        'name' => 'Música',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'music-note-beamed',
        'icon_url' => '/icons/bootstrap/music-note-beamed.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_mic',
        'name' => 'Microfone',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'mic',
        'icon_url' => '/icons/bootstrap/mic.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_mic_fill',
        'name' => 'Microfone fill',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'mic-fill',
        'icon_url' => '/icons/bootstrap/mic-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_volume_up_fill',
        'name' => 'Volume',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'volume-up-fill',
        'icon_url' => '/icons/bootstrap/volume-up-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_volume_mute_fill',
        'name' => 'Mudo',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'volume-mute-fill',
        'icon_url' => '/icons/bootstrap/volume-mute-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_broadcast',
        'name' => 'Live',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'broadcast',
        'icon_url' => '/icons/bootstrap/broadcast.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_webcam',
        'name' => 'Webcam',
        'group' => 'bs_media',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'webcam',
        'icon_url' => '/icons/bootstrap/webcam.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chat',
        'name' => 'Chat',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chat',
        'icon_url' => '/icons/bootstrap/chat.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chat_dots',
        'name' => 'Chat dots',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chat-dots',
        'icon_url' => '/icons/bootstrap/chat-dots.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chat_dots_fill',
        'name' => 'Chat fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chat-dots-fill',
        'icon_url' => '/icons/bootstrap/chat-dots-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_envelope',
        'name' => 'E-mail',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'envelope',
        'icon_url' => '/icons/bootstrap/envelope.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_envelope_fill',
        'name' => 'E-mail fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'envelope-fill',
        'icon_url' => '/icons/bootstrap/envelope-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_telephone',
        'name' => 'Telefone',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'telephone',
        'icon_url' => '/icons/bootstrap/telephone.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_telephone_fill',
        'name' => 'Telefone fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'telephone-fill',
        'icon_url' => '/icons/bootstrap/telephone-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_megaphone',
        'name' => 'Megafone',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'megaphone',
        'icon_url' => '/icons/bootstrap/megaphone.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_megaphone_fill',
        'name' => 'Megafone fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'megaphone-fill',
        'icon_url' => '/icons/bootstrap/megaphone-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_send',
        'name' => 'Enviar',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'send',
        'icon_url' => '/icons/bootstrap/send.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_send_fill',
        'name' => 'Enviar fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'send-fill',
        'icon_url' => '/icons/bootstrap/send-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_inbox',
        'name' => 'Inbox',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'inbox',
        'icon_url' => '/icons/bootstrap/inbox.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bell',
        'name' => 'Notificação',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bell',
        'icon_url' => '/icons/bootstrap/bell.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bell_fill',
        'name' => 'Notificação fill',
        'group' => 'bs_communication',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bell-fill',
        'icon_url' => '/icons/bootstrap/bell-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cart',
        'name' => 'Carrinho',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cart',
        'icon_url' => '/icons/bootstrap/cart.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cart_fill',
        'name' => 'Carrinho fill',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cart-fill',
        'icon_url' => '/icons/bootstrap/cart-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bag',
        'name' => 'Sacola',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bag',
        'icon_url' => '/icons/bootstrap/bag.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bag_fill',
        'name' => 'Sacola fill',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bag-fill',
        'icon_url' => '/icons/bootstrap/bag-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_credit_card',
        'name' => 'Cartão',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'credit-card',
        'icon_url' => '/icons/bootstrap/credit-card.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_credit_card_fill',
        'name' => 'Cartão fill',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'credit-card-fill',
        'icon_url' => '/icons/bootstrap/credit-card-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_currency_dollar',
        'name' => 'Dólar',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'currency-dollar',
        'icon_url' => '/icons/bootstrap/currency-dollar.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_shop',
        'name' => 'Loja',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'shop',
        'icon_url' => '/icons/bootstrap/shop.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_tag',
        'name' => 'Etiqueta',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'tag',
        'icon_url' => '/icons/bootstrap/tag.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_tag_fill',
        'name' => 'Etiqueta fill',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'tag-fill',
        'icon_url' => '/icons/bootstrap/tag-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_gift',
        'name' => 'Presente',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'gift',
        'icon_url' => '/icons/bootstrap/gift.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_gift_fill',
        'name' => 'Presente fill',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'gift-fill',
        'icon_url' => '/icons/bootstrap/gift-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_ticket_perforated',
        'name' => 'Ingresso',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'ticket-perforated',
        'icon_url' => '/icons/bootstrap/ticket-perforated.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_percent',
        'name' => 'Desconto',
        'group' => 'bs_commerce',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'percent',
        'icon_url' => '/icons/bootstrap/percent.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_check',
        'name' => 'Check',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'check',
        'icon_url' => '/icons/bootstrap/check.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_check_circle',
        'name' => 'Check círculo',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'check-circle',
        'icon_url' => '/icons/bootstrap/check-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_check_circle_fill',
        'name' => 'Check círculo fill',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'check-circle-fill',
        'icon_url' => '/icons/bootstrap/check-circle-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_x',
        'name' => 'Fechar',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'x',
        'icon_url' => '/icons/bootstrap/x.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_x_circle',
        'name' => 'X círculo',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'x-circle',
        'icon_url' => '/icons/bootstrap/x-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_x_circle_fill',
        'name' => 'X círculo fill',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'x-circle-fill',
        'icon_url' => '/icons/bootstrap/x-circle-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_plus',
        'name' => 'Mais',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'plus',
        'icon_url' => '/icons/bootstrap/plus.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_plus_circle',
        'name' => 'Mais círculo',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'plus-circle',
        'icon_url' => '/icons/bootstrap/plus-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_dash',
        'name' => 'Menos',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'dash',
        'icon_url' => '/icons/bootstrap/dash.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_exclamation_circle',
        'name' => 'Alerta',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'exclamation-circle',
        'icon_url' => '/icons/bootstrap/exclamation-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_question_circle',
        'name' => 'Ajuda',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'question-circle',
        'icon_url' => '/icons/bootstrap/question-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_info_circle',
        'name' => 'Info',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'info-circle',
        'icon_url' => '/icons/bootstrap/info-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_gear',
        'name' => 'Configurações',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'gear',
        'icon_url' => '/icons/bootstrap/gear.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_gear_fill',
        'name' => 'Config fill',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'gear-fill',
        'icon_url' => '/icons/bootstrap/gear-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_sliders',
        'name' => 'Sliders',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'sliders',
        'icon_url' => '/icons/bootstrap/sliders.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_search',
        'name' => 'Buscar',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'search',
        'icon_url' => '/icons/bootstrap/search.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_list',
        'name' => 'Lista',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'list',
        'icon_url' => '/icons/bootstrap/list.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_grid_3x3_gap',
        'name' => 'Grid',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'grid-3x3-gap',
        'icon_url' => '/icons/bootstrap/grid-3x3-gap.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_eye',
        'name' => 'Ver',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'eye',
        'icon_url' => '/icons/bootstrap/eye.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_eye_fill',
        'name' => 'Ver fill',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'eye-fill',
        'icon_url' => '/icons/bootstrap/eye-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_eye_slash',
        'name' => 'Ocultar',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'eye-slash',
        'icon_url' => '/icons/bootstrap/eye-slash.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_trash',
        'name' => 'Lixeira',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'trash',
        'icon_url' => '/icons/bootstrap/trash.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_trash_fill',
        'name' => 'Lixeira fill',
        'group' => 'bs_ui',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'trash-fill',
        'icon_url' => '/icons/bootstrap/trash-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_right',
        'name' => 'Seta direita',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-right',
        'icon_url' => '/icons/bootstrap/arrow-right.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_left',
        'name' => 'Seta esquerda',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-left',
        'icon_url' => '/icons/bootstrap/arrow-left.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_up',
        'name' => 'Seta cima',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-up',
        'icon_url' => '/icons/bootstrap/arrow-up.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_down',
        'name' => 'Seta baixo',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-down',
        'icon_url' => '/icons/bootstrap/arrow-down.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_up_right',
        'name' => 'Seta diagonal',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-up-right',
        'icon_url' => '/icons/bootstrap/arrow-up-right.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chevron_right',
        'name' => 'Chevron direita',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chevron-right',
        'icon_url' => '/icons/bootstrap/chevron-right.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chevron_left',
        'name' => 'Chevron esquerda',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chevron-left',
        'icon_url' => '/icons/bootstrap/chevron-left.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chevron_up',
        'name' => 'Chevron cima',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chevron-up',
        'icon_url' => '/icons/bootstrap/chevron-up.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_chevron_down',
        'name' => 'Chevron baixo',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'chevron-down',
        'icon_url' => '/icons/bootstrap/chevron-down.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_caret_right_fill',
        'name' => 'Caret direita',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'caret-right-fill',
        'icon_url' => '/icons/bootstrap/caret-right-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_caret_left_fill',
        'name' => 'Caret esquerda',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'caret-left-fill',
        'icon_url' => '/icons/bootstrap/caret-left-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_box_arrow_up_right',
        'name' => 'Link externo',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'box-arrow-up-right',
        'icon_url' => '/icons/bootstrap/box-arrow-up-right.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_repeat',
        'name' => 'Repetir',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-repeat',
        'icon_url' => '/icons/bootstrap/arrow-repeat.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_arrow_clockwise',
        'name' => 'Atualizar',
        'group' => 'bs_arrows',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'arrow-clockwise',
        'icon_url' => '/icons/bootstrap/arrow-clockwise.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person',
        'name' => 'Pessoa',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person',
        'icon_url' => '/icons/bootstrap/person.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person_fill',
        'name' => 'Pessoa fill',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person-fill',
        'icon_url' => '/icons/bootstrap/person-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_people',
        'name' => 'Grupo',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'people',
        'icon_url' => '/icons/bootstrap/people.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_people_fill',
        'name' => 'Grupo fill',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'people-fill',
        'icon_url' => '/icons/bootstrap/people-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person_circle',
        'name' => 'Avatar',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person-circle',
        'icon_url' => '/icons/bootstrap/person-circle.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person_badge',
        'name' => 'Crachá',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person-badge',
        'icon_url' => '/icons/bootstrap/person-badge.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person_hearts',
        'name' => 'Fãs',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person-hearts',
        'icon_url' => '/icons/bootstrap/person-hearts.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_person_workspace',
        'name' => 'Workspace',
        'group' => 'bs_people',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'person-workspace',
        'icon_url' => '/icons/bootstrap/person-workspace.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_file_earmark',
        'name' => 'Arquivo',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'file-earmark',
        'icon_url' => '/icons/bootstrap/file-earmark.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_file_earmark_text',
        'name' => 'Documento',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'file-earmark-text',
        'icon_url' => '/icons/bootstrap/file-earmark-text.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_file_earmark_pdf',
        'name' => 'PDF',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'file-earmark-pdf',
        'icon_url' => '/icons/bootstrap/file-earmark-pdf.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_file_earmark_image',
        'name' => 'Arquivo imagem',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'file-earmark-image',
        'icon_url' => '/icons/bootstrap/file-earmark-image.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_folder',
        'name' => 'Pasta',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'folder',
        'icon_url' => '/icons/bootstrap/folder.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_folder_fill',
        'name' => 'Pasta fill',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'folder-fill',
        'icon_url' => '/icons/bootstrap/folder-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_download',
        'name' => 'Download',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'download',
        'icon_url' => '/icons/bootstrap/download.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_upload',
        'name' => 'Upload',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'upload',
        'icon_url' => '/icons/bootstrap/upload.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_link_45deg',
        'name' => 'Link',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'link-45deg',
        'icon_url' => '/icons/bootstrap/link-45deg.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_paperclip',
        'name' => 'Anexo',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'paperclip',
        'icon_url' => '/icons/bootstrap/paperclip.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_clipboard',
        'name' => 'Clipboard',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'clipboard',
        'icon_url' => '/icons/bootstrap/clipboard.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_save',
        'name' => 'Salvar',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'save',
        'icon_url' => '/icons/bootstrap/save.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_save_fill',
        'name' => 'Salvar fill',
        'group' => 'bs_files',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'save-fill',
        'icon_url' => '/icons/bootstrap/save-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_laptop',
        'name' => 'Notebook',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'laptop',
        'icon_url' => '/icons/bootstrap/laptop.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_phone',
        'name' => 'Celular',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'phone',
        'icon_url' => '/icons/bootstrap/phone.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_tablet',
        'name' => 'Tablet',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'tablet',
        'icon_url' => '/icons/bootstrap/tablet.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_display',
        'name' => 'Monitor',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'display',
        'icon_url' => '/icons/bootstrap/display.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_wifi',
        'name' => 'Wi-Fi',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'wifi',
        'icon_url' => '/icons/bootstrap/wifi.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cloud',
        'name' => 'Nuvem',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cloud',
        'icon_url' => '/icons/bootstrap/cloud.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cloud_fill',
        'name' => 'Nuvem fill',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cloud-fill',
        'icon_url' => '/icons/bootstrap/cloud-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_bluetooth',
        'name' => 'Bluetooth',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'bluetooth',
        'icon_url' => '/icons/bootstrap/bluetooth.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cpu',
        'name' => 'CPU',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cpu',
        'icon_url' => '/icons/bootstrap/cpu.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_hdd',
        'name' => 'HD',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'hdd',
        'icon_url' => '/icons/bootstrap/hdd.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_code_slash',
        'name' => 'Código',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'code-slash',
        'icon_url' => '/icons/bootstrap/code-slash.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_terminal',
        'name' => 'Terminal',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'terminal',
        'icon_url' => '/icons/bootstrap/terminal.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_robot',
        'name' => 'Robô',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'robot',
        'icon_url' => '/icons/bootstrap/robot.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_lightning_charge',
        'name' => 'Energia',
        'group' => 'bs_tech',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'lightning-charge',
        'icon_url' => '/icons/bootstrap/lightning-charge.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_geo_alt',
        'name' => 'Local',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'geo-alt',
        'icon_url' => '/icons/bootstrap/geo-alt.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_geo_alt_fill',
        'name' => 'Local fill',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'geo-alt-fill',
        'icon_url' => '/icons/bootstrap/geo-alt-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_pin_map',
        'name' => 'Pin mapa',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'pin-map',
        'icon_url' => '/icons/bootstrap/pin-map.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_pin_map_fill',
        'name' => 'Pin fill',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'pin-map-fill',
        'icon_url' => '/icons/bootstrap/pin-map-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_compass',
        'name' => 'Bússola',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'compass',
        'icon_url' => '/icons/bootstrap/compass.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_house',
        'name' => 'Casa',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'house',
        'icon_url' => '/icons/bootstrap/house.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_house_fill',
        'name' => 'Casa fill',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'house-fill',
        'icon_url' => '/icons/bootstrap/house-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_building',
        'name' => 'Prédio',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'building',
        'icon_url' => '/icons/bootstrap/building.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_clock',
        'name' => 'Relógio',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'clock',
        'icon_url' => '/icons/bootstrap/clock.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_clock_fill',
        'name' => 'Relógio fill',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'clock-fill',
        'icon_url' => '/icons/bootstrap/clock-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_calendar_event',
        'name' => 'Calendário',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'calendar-event',
        'icon_url' => '/icons/bootstrap/calendar-event.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_alarm',
        'name' => 'Alarme',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'alarm',
        'icon_url' => '/icons/bootstrap/alarm.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_sun',
        'name' => 'Sol',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'sun',
        'icon_url' => '/icons/bootstrap/sun.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_moon',
        'name' => 'Lua',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'moon',
        'icon_url' => '/icons/bootstrap/moon.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_cloud_sun',
        'name' => 'Clima',
        'group' => 'bs_location',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'cloud-sun',
        'icon_url' => '/icons/bootstrap/cloud-sun.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_pencil',
        'name' => 'Lápis',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'pencil',
        'icon_url' => '/icons/bootstrap/pencil.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_pencil_fill',
        'name' => 'Lápis fill',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'pencil-fill',
        'icon_url' => '/icons/bootstrap/pencil-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_brush',
        'name' => 'Pincel',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'brush',
        'icon_url' => '/icons/bootstrap/brush.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_palette',
        'name' => 'Paleta',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'palette',
        'icon_url' => '/icons/bootstrap/palette.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_palette_fill',
        'name' => 'Paleta fill',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'palette-fill',
        'icon_url' => '/icons/bootstrap/palette-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_scissors',
        'name' => 'Tesoura',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'scissors',
        'icon_url' => '/icons/bootstrap/scissors.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_magic',
        'name' => 'Mágica',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'magic',
        'icon_url' => '/icons/bootstrap/magic.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_stars',
        'name' => 'Estrelas',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'stars',
        'icon_url' => '/icons/bootstrap/stars.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_award',
        'name' => 'Prêmio',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'award',
        'icon_url' => '/icons/bootstrap/award.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_trophy',
        'name' => 'Troféu',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'trophy',
        'icon_url' => '/icons/bootstrap/trophy.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_trophy_fill',
        'name' => 'Troféu fill',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'trophy-fill',
        'icon_url' => '/icons/bootstrap/trophy-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_lightbulb',
        'name' => 'Ideia',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'lightbulb',
        'icon_url' => '/icons/bootstrap/lightbulb.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_lightbulb_fill',
        'name' => 'Ideia fill',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'lightbulb-fill',
        'icon_url' => '/icons/bootstrap/lightbulb-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_book',
        'name' => 'Livro',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'book',
        'icon_url' => '/icons/bootstrap/book.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_mortarboard',
        'name' => 'Formatura',
        'group' => 'bs_creative',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'mortarboard',
        'icon_url' => '/icons/bootstrap/mortarboard.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_lock',
        'name' => 'Cadeado',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'lock',
        'icon_url' => '/icons/bootstrap/lock.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_lock_fill',
        'name' => 'Cadeado fill',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'lock-fill',
        'icon_url' => '/icons/bootstrap/lock-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_unlock',
        'name' => 'Aberto',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'unlock',
        'icon_url' => '/icons/bootstrap/unlock.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_unlock_fill',
        'name' => 'Aberto fill',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'unlock-fill',
        'icon_url' => '/icons/bootstrap/unlock-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_shield',
        'name' => 'Escudo',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'shield',
        'icon_url' => '/icons/bootstrap/shield.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_shield_fill',
        'name' => 'Escudo fill',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'shield-fill',
        'icon_url' => '/icons/bootstrap/shield-fill.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_shield_check',
        'name' => 'Verificado',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'shield-check',
        'icon_url' => '/icons/bootstrap/shield-check.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_key',
        'name' => 'Chave',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'key',
        'icon_url' => '/icons/bootstrap/key.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
    [
        'slug' => 'bs_fingerprint',
        'name' => 'Digital',
        'group' => 'bs_security',
        'type' => 'svg_icon',
        'icon_set' => 'bootstrap',
        'icon_name' => 'fingerprint',
        'icon_url' => '/icons/bootstrap/fingerprint.svg',
        'fill' => '#ffffff',
        'size' => 120,
    ],
],
];
